env:
    - ARCH=x86
language: python
sudo: false
python:
    - "2.7"
cache:
  directories:
    - "$HOME/.pip-cache/"
    - "/home/travis/virtualenv/python2.7"
install:
    - "apt-get update"
    - "apt-get upgrade --yes"
    - "apt-get install nano git-core python-dev bison libasound2-dev libportaudio-dev python-pyaudio --yes"
    - "apt-get remove python-pip"
    - "easy_install pip"

before_script:
    - "flake8 mypa.py client tests"
script:
    - "coverage run -m unittest discover"
after_success:
    - "coverage report"
    - "coveralls"
